### PR TITLE
dev

### PR DESCRIPTION
**Pull request by mac-zhou**
#6 test HA 59.2
#7 support miio new version

### CODE REVIEW

**Comment by cxlwill** [comment]
`ImportError: cannot import name 'AirConditioningCompanion'`

是不是没提交到 Python-miio 要手动拖库？

**Comment by 0xbw** [comment]
@cxlwill 是python-miio还没出release， 所以暂时只能拖库重新安装miio
现在的版本不要测试，需要测试的话，我在这里说一下

**Comment by samuck1** [comment]
Work in hassio 80.3?
I cant switch off the Air conditioner
